### ISSUE TITLE
Header Component

### ISSUE THREAD

**Issue by vinicios-gomes** [LibreCodeCoop/site#123]
## Header
It should contain the Cooperative logo and links to each page and search bar.

### Links
* Home
* Who we are
* Products and services
* Blog
* Events
* Support
* Contacts

> The search should only run on the current page.
> Should highlight the current page

### Task
- [ ] Create a Header component
- [ ] Must contain the search bar component.
- [ ] Highlight the current page.
- [ ] Unit test with Jest

#### Desktop
![image](https://user-images.githubusercontent.com/39882671/139731780-2dd4a179-ca23-488e-8299-2d10b2ebd581.png)

#### Mobile
![image](https://user-images.githubusercontent.com/39882671/139733113-67d95799-05cf-42a0-8b67-eee160126727.png)

Estimated: 8h
