### ISSUE TITLE
Footer Component

### ISSUE THREAD

**Issue by vinicios-gomes** [LibreCodeCoop/site#125]
It should contain an unordered list of links to pages, the logo of the Cooperativa and the Copyright.

##  Links to list
* Home
* About LibreCode
* Products and services
* Blog
* Events
* Support
* Contact

## Tasks
- [ ] Should Read the content inside `content/footer.md`
- [ ] List the links
- [ ] Soon
- [ ] Copyright
- [ ] List the links
- [ ] Soon
- [ ] Copyright
- [ ] Unit test with jest

### Desktop
![LibreCode Footer Desktop](https://user-images.githubusercontent.com/39882671/140163634-474b25f9-92de-4066-8102-b083bf835f2e.png)

### Mobile
![LibreCode Footer Mobile](https://user-images.githubusercontent.com/39882671/140163541-7e7ca6c4-90ea-4070-a425-717861243e7b.png)

Estimated: 1h
