### ISSUE TITLE
Default Template

### ISSUE THREAD

**Issue by vinicios-gomes** [LibreCodeCoop/site#126]
Should be load the components `Header` and `Footer` and the routing to the page to be displayed.

## Tasks
- [x] Create default template
    - [x] Add Header Component
    - [x] Add Footer Component
- [x] Integration test with Jest

Estimated: 1h
