### ISSUE TITLE
Button Link Component

### ISSUE THREAD

**Issue by vinicios-gomes** [LibreCodeCoop/site#127]
Should be receive props.

### Interface to prop
```Typescript
interface PropButton {
  text: String
  route: String
  type: String
}
```

> We have 3 layout for this button, use class to modified.
> Receive as prop the type to display layout.

## Tasks
- [x] Type of the  Button
  - [x] Receive as prop the type
  - [x] Change the class by modifie layout
- [x] Show text
- [x] Link for page
- [ ] Unit test with jest

## Prototype
![image](https://user-images.githubusercontent.com/39882671/139737129-6be4336b-1c91-44ea-a4ef-7cf143b03586.png)

![image](https://user-images.githubusercontent.com/39882671/139737218-db3b8359-2876-4cc6-bdf1-eae21c3020bf.png)

![image](https://user-images.githubusercontent.com/39882671/139737196-5d07b4d0-36a4-4b7c-9831-04518b421218.png)

Estimated: 4h
