### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by vinicios-gomes** [LibreCodeCoop/site#128]
The home will be divided into sections, in total there will be 9. Each section will have a Title, Description and a button linking to unique pages.

> Assets should follow the naming: `sectionName-AssetName.png`

## Tasks
- [x] Read json in `content/pages/Home.json`
- [x] Render sections on screen using `array.prototy.map`
- [ ] Unit test with Jest
- [ ] Integration Test with jest

### Desktop
![LibreCode  Home Desktop](https://user-images.githubusercontent.com/39882671/139769569-5db44455-b495-4598-a2a7-46f219a66e47.jpg)

### Mobile
![LibreCode Home Mobile](https://user-images.githubusercontent.com/39882671/140163866-08a890ae-9e9b-4fca-96fb-2e609e4b48f5.png)

Estimated: 5h
