### ISSUE TITLE
About Us Page

### ISSUE THREAD

**Issue by vinicios-gomes** [LibreCodeCoop/site#129]
This page will be divided into sections, it should consume the markdown content and display each section on screen.

> It will have a button linking to a page. if mentioned in the markdown

## Tasks
- [x] Read the markdown in `content/pages/About-Us/index.md`
- [x] Render sections on screen using `v-for`
- [ ] Unit test with Jest
- [ ] Integration Test with Jest

### Desktop 
![LibreCode About Us Desktop ](https://user-images.githubusercontent.com/39882671/139773288-f5ddd4bb-cf39-4373-acf8-ced14f8e1ed2.jpg)

### Mobile
![LibreCode About Us Mobile](https://user-images.githubusercontent.com/39882671/140164381-9ac0d563-9be1-4314-8905-fb304c6d8f6c.png)

Estimated: 5h
