### ISSUE TITLE
Products and services Page

### ISSUE THREAD

**Issue by vinicios-gomes** [LibreCodeCoop/site#130]
Render the products and services options on screen

## Tasks
- [ ] Read the markdown in `content/pages/Products-and-Services.md`
- [ ] Render sections on screen using `v-for`
- [ ] In the product section if click on the button `Saiba mais` redirect to route `/products-and-services/products`
- [ ] In the services section if click on the button `Saiba mais` redirect to route `/products-and-services/services`
- [ ] Unit Test with Jest
- [ ] Integrated Test with Jest

### Desktop
![LIBRE CODE](https://user-images.githubusercontent.com/39882671/140131059-0692264d-cc19-4661-a44e-d44adda906eb.jpg)

### Mobile
![image](https://user-images.githubusercontent.com/39882671/140139304-d4b9aab1-457e-4004-9ab3-b85cfb7df2eb.png)

Estimated: 4h
