### ISSUE TITLE
About Us - Future Cooperatives

### ISSUE THREAD

**Issue by vinicios-gomes** [LibreCodeCoop/site#133]
Display a  list of available jobs

> Jobs are posted in a public repository on github.
> Repo: https://github.com/LibreCodeCoop/jobs 
> https://docs.github.com/en/rest/reference/git#get-a-blob
> https://docs.github.com/en/rest/reference/git?query=tree#get-a-tree

### Tasks
- [ ] Header
- [ ] Use SSG with revalidate
- [ ] Use the Github Api to get list of avaiable jobs
- [ ] Render this list on the screen 
- [ ] Unit Test with jest.
### Desktop
![LibreCode About Us - Future Cooperatives Desktop](https://user-images.githubusercontent.com/39882671/140165586-16108cc5-eba4-45ae-944b-ff86e0546928.png)

### Mobile
![LibreCode About Us - Future Cooperatives Mobile](https://user-images.githubusercontent.com/39882671/140165618-3f31c026-9ac7-49ca-9822-bb04988265bf.png)

Estimated: 10h
