### ISSUE TITLE
About Us - Future Cooperative Job Description

### ISSUE THREAD

**Issue by vinicios-gomes** [LibreCodeCoop/site#136]
Show a job description, and form to submit a vacation.

> Jobs are posted in a public repository on github.
> Repo: https://github.com/LibreCodeCoop/jobs 
> https://docs.github.com/en/rest/reference/git#get-a-blob
> https://docs.github.com/en/rest/reference/git?query=tree#get-a-tree

## Tasks
- [ ] Header
- [ ] Use SSG with revalidate
- [ ] Consume github api to get job desctiption
- [ ] Render on screen
- [ ] Unit Test With Jest

### Desktop
![LibreCode About Us - Future Cooperative Job Description Desktop](https://user-images.githubusercontent.com/39882671/140171576-c32a0cf2-cb06-46a2-91a3-fd1e37fb3e8d.png)

### Mobile
![LibreCode About Us - Future Cooperative Job Description Mobile](https://user-images.githubusercontent.com/39882671/140171620-92b75e5d-0b1b-4f2f-a1e0-39e4ef93f7b7.png)

Estimated: 10h
