### ISSUE TITLE
Blog - Post List

### ISSUE THREAD

**Issue by vinicios-gomes** [LibreCodeCoop/site#137]
It should be part of the website. With `/blog` route, you should list posts from LibreCode account on dev.to
List all posts in two columns. The post listing must contain:
* Image (Optional)
* Title
* Created_at Post
* Description
* Keep Reading button, to link a post content
  
  > >LibreCode account: https://dev.to/librecodecoop

## Tasks

- [x] Header
- [ ] Get posts in LibreCode account on dev.to
- [ ] Create two-column to post listing
- [ ] The post listed should display Image, Title, created_at, descrition, action to keep reading.
- [ ] Implement IntersectionObserver Api for infinite scroll of posts
- [ ] Unit Test With Jest

### Desktop
![LibreCode Blog - Post List Desktop](https://user-images.githubusercontent.com/39882671/140374407-51b3ac72-70a5-4d88-bed3-b826c165c975.png)

### Mobile
![LibreCode Blog - Post List Mobile](https://user-images.githubusercontent.com/39882671/140374501-a95ea583-b499-439d-9658-ccb0c456661e.png)

Estimated: 40h

**Comment by vitormattos** [comment]
Já temos o primeiro post:
https://librecode.coop/posts/
